# Generated by Django 2.2.5 on 2019-10-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191011_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_numbers',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Person')),
            ],
        ),
    ]
