# Generated by Django 2.2.5 on 2019-10-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191015_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
